### ISSUE TITLE
VSIX Publishing to MyGet Feed

### ISSUE THREAD

**Issue by cleemullins** [sboulema/VsixTools#1]
@sboulema - this is a great package you've got! We're using this for updating the versions of the VSIX as part of our daily process and it's working great. 

I might suggest you make the "publish" a bit richer. Today you only push to the marketplace, which doesn't always make sense for a CI/CD process. 

For example, our daily builds go to a MyGet feed (botbuilder.myget.org), which supports the VSIX protocols and gives us a nice way to test/iterate on these without having to publish to the official marketplace. To get this working in the short term, I just added a command step and used curl:

`curl -X POST --verbose --data-binary @"$(build.artifactstagingdirectory)\templates\Enterprise-Template\EnterpriseBotVSIX\bin\$(BuildConfiguration)\EnterpriseBotTemplate.vsix" -H "X-NuGet-ApiKey: $(PublishMyGetKey)" https://botbuilder.myget.org/F/aitemplates/vsix/upload`

... but I would really like to replace this with a dedicated step. It'll make the long-term maintenance of the build much easier, as dedicated scripts are difficult to work with and maintain.

Nice Work!

**Comment by sboulema** [comment]
Thanks! Great to hear the extension is being used :)

Grab the new release for a richer upload task!
Be aware that it contains some breaking changes, so please read the updated documentation.
