### ISSUE TITLE
Specify timestamp URL?

### ISSUE THREAD

**Issue by nbelyh** [sboulema/VsixTools#10]
There is no option to specify timestamp URL for the signing. This appears to be a problem, because the signature without timestamp will expire when the certificate expires.
Or am I missing something?

**Comment by sboulema** [comment]
Will look into adding this!

**Comment by nbelyh** [comment]
Thanks 👍

**Comment by sboulema** [comment]
New version is now available! :rocket:

**Comment by nbelyh** [comment]
Dear @sboulema, please note that the timestamping did not really work for me when I tried - I ended up writing a custom powershell script for signing and uninstalling the extension...  Looks like there are options for timestamping algorithm, like SHA1 vs SHA2. It seems you have added the option `/t` which appears to be for SHA1 and does not seem to be working probably because SHA1 was banned two years ago. The parameters that did works for me are: `/tr $timestampUrl /td sha256`. Maybe it depends on the specific timestamp server type though.

**Comment by sboulema** [comment]
Released a new version with the /tr and /td options! 🚀
