### ISSUE TITLE
publish privately

### ISSUE THREAD

**Issue by uajvi** [sboulema/VsixTools#11]
Hello I have an extension but i don't want to publish to public market place, how can i publish privately with your extension automatically. Because i see below 3 options only. can you help me to add a step to publish privately as well?

Uploads the vsix to the Open VSIX gallery.
Uploads the vsix to a MyGet Vsix Feed.
Uploads the vsix to the Visual Studio Marketplace.

**Comment by sboulema** [comment]
You can set the private variable to true in the publish-manifest.json.

Does that solve your problem?
