### ISSUE TITLE
Warning running task VsixToolsUpdateVersion

### ISSUE THREAD

**Issue by laurentkempe** [sboulema/VsixTools#12]
Any clue why I start to get that warning lately in Azure DevOps logs of my build?

`##[warning]Task 'VsixToolsUpdateVersion' (1.0.0) is using deprecated task execution handler. The task should use the supported task-lib: https://aka.ms/tasklib`

**Comment by sboulema** [comment]
Thanks for reporting!

Should be fixed in the new release 🚀
