### ISSUE TITLE
Signing of vsix failed because $tempDirectory is not filled in any cases

### ISSUE THREAD

**Issue by gclpixel** [sboulema/VsixTools#13]
in your powershell script for signing the vsix files the tempdirectory for downloading is missing if you don't use PAT and username.

to code to fill the $tempDiecrory variable is only set inside of the "if" statement.

`$tempDirectory = Get-VstsTaskVariable -Name "Agent.TempDirectory" -Require`

**Comment by sboulema** [comment]
Thanks for reporting!

Grab the new release. 🚀

**Comment by gclpixel** [comment]
Thank you.
Fix is working
