### ISSUE TITLE
Using deprecated task execution handler

### ISSUE THREAD

**Issue by laurentkempe** [sboulema/VsixTools#18]
I get the following warning while using your great VsixToolsUpdateVersion 

    ##[warning]Task 'VsixToolsUpdateVersion' (1.0.0) is using deprecated task execution handler. The task should use the supported task-lib: https://aka.ms/tasklib

**Comment by sboulema** [comment]
Are you using the 2.* version of the task?

**Comment by laurentkempe** [comment]
No, I am using  the version 1

**Comment by laurentkempe** [comment]
With version 2, I don't get this warning anymore! 👍
