### ISSUE TITLE
Locate Visual Studio instance with VS SDK component

### ISSUE THREAD

**Issue by jcansdale** [sboulema/VsixTools#4]
Hello 👋 

I started working on a VSIX publishing task and stumbled across yours when searching for prior art. 🎉 I'm new to Azure task extensions, so looking through your script will be interesting!

I notice that you're locating the Visual Studio 2017 install directory by reading from the, `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\VisualStudio\SxS\VS7` registry key. I never knew this existed for Visual Studio 2017.

https://github.com/sboulema/VsixTools/blob/master/src/tasks/uploadVsix/uploadVsix.ps1#L92-L94

I have a bunch of Visual Studio 2017 instances installed and on my machine this registry key points to: `C:\Program Files (x86)\Microsoft Visual Studio\Preview\Community\`. As it happens, this does have the VS SDK installed but it might not have.

The way I've been locating Visual Studio in my publish script is using the `VSSetup` module and searching for an instance of Visual Studio with the 'Microsoft.VisualStudio.Component.VSSDK' component installed.

https://github.com/jcansdale/TemporaryProjects/blob/master/Publish-Vsix.ps1#L20-L25

Perhaps you could fall back to doing this if a file doesn't exist at `$VSIXPublisherPath`?

**Comment by sboulema** [comment]
Thanks for reporting and solving :D
