### ISSUE TITLE
Can't always find *.vsix artifact in Working Directory

### ISSUE THREAD

**Issue by jcansdale** [sboulema/VsixTools#5]
I've started using the `Upload Vsix` task on a couple of my projects.

On the first one I tried configuring, it wasn't able to find my VSIX artifact until I changed the `Working Directory` to be a fully qualified name:
```
$(System.ArtifactsDirectory)\$(Release.PrimaryArtifactSourceAlias)\drop\TemporaryProjects.Vsix\bin\Release\TemporaryProjects.vsix
```

When I tried without a fully qualified name, I got the following:
```
2018-10-07T08:09:29.4941591Z ##[error]VSSDK: error VsixPub0001 : Cannot find payload at specified path: 'D:\a\r1\a\_TemporaryProjects-.NET Desktop-CI\drop\TemporaryProjects.Vsix'.
2018-10-07T08:09:29.5428043Z ##[section]Finishing: Upload Vsix
```

I think this might be because the project that packages the extension includes `.Vsix` in its name (`TemporaryProjects.Vsix`). I like to keep the project that packages the .vsix separate from the extension code itself. This allows my unit tests to run faster because it doesn't need to package and deploy the extension every time I change something.

It also wasn't obvious that `Working Directory` was the directory containing the .vsix file.

It would be more obvious what was going on if this field started off with a default value of, `**\*.vsix`. The user could then see immediately what this was looking for and how it could be changed to be more explicit (pointing to a different directory or .vsix file).

Does that make sense?

**Comment by jcansdale** [comment]
I tried executing:
```ps1
(Get-ChildItem "C:\Source\github.com\jcansdale\TemporaryProjects" -Recurse -Include *.vsix)
```
from
https://github.com/sboulema/VsixTools/blob/7ba37fe95d4ec0d5f7eb16865c973a355bd95ad8/src/tasks/uploadVsix/uploadVsix.ps1#L98

```
    Directory: C:\Source\github.com\jcansdale\TemporaryProjects


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       25/09/2018  12:34 AM                TemporaryProjects.Vsix


    Directory: C:\Source\github.com\jcansdale\TemporaryProjects\TemporaryProjects.Vsix\bin\Debug


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       24/09/2018  11:39 PM        1038731 TemporaryProjects.vsix
```

You can see it's matching the `TemporaryProjects.Vsix` directory before the `TemporaryProjects.vsix` file. This seems to be why the task is failing.

I think the simple fix would be adding a `-File`:
```ps1
(Get-ChildItem "C:\Source\github.com\jcansdale\TemporaryProjects" -Recurse -Include *.vsix -File)
```

**Comment by sboulema** [comment]
Thanks for reporting and solving :D
