### ISSUE TITLE
Make secure file (username/PAT) optional?

### ISSUE THREAD

**Issue by nbelyh** [sboulema/VsixTools#9]
For example, the secure file is already downloaded for my build, using the standard "download secure file" task. Would it be possible to just use that file? Now the "username" and "PAT" are appear to be required?

The "download secure file" task:
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-secure-file

**Comment by sboulema** [comment]
Will look at making this scenario possible!

**Comment by sboulema** [comment]
New version is now available! :rocket:
